- readme.md
Right now, the logo just goes to the SVG. I figure clicking it might as well go somewhere useful - like the unified website.
> docs(README.md): Add link to website to logo

- package.json
- readme.md
- types/index.d.ts
- types/tsconfig.json
- types/tslint.json
- types/unified-tests.ts
This is the first try to implement type definitions for unified.
I knew there is another attempt to adding types. But, I don't think the processor should persist AST type. It would make users confused because it looks tricky and doesn't work well with presets.
https://github.com/hrajchert/unified-typings-test/blob/master/src/types/unified/unified.d.ts
> Add type definitions

- readme.md
The introductory README lacks information on how to get help when using Unified. This pull requests  orientate users on how to get their questions answered or help others by pointing them to our already existing **[Unified community on Spectrum](https://spectrum.chat/unified)**.
The community itself is already in the README but I wasn't aware it was a thing – it might be the case for others too. Hopefully this will increase visibility!
> Add Spectrum info on how to get help

- package.json
`unist` and `vfile` both already ship with types so removing the `@types/*` `DefinitelyTyped` definitions doesn't cause any issues. Ran `yarn test` and no complaints there.
> use unist, vfile types instead of definitelytyped

- types/index.d.ts
- types/tsconfig.json
- types/unified-tests.ts
This PR fixes #56 by correcting the TypeScript definitions to properly reflect the fact that Unified exports a CommonJS module rather than an ESM module. 
* Replaced incorrect `export default`  syntax with `export =`
* Wrapped all the TypeScript type definitions in a namespace
> Corrected type definitions. Fixes #56

- types/index.d.ts
- types/tslint.json
- types/unified-tests.ts
An initial implementation for https://github.com/remarkjs/remark/pull/383#discussion_r299623495
> Unified types would highly benefit from a generic here. As written, options passed along with the use() call is a place where all type safety is lost.
This makes plugins generic, defaulting to unified's `Settings` type.
Plugins that do not specify a settings interface should *not* be unaffected.
> allow plugins to declare an interface for their settings

- types/index.d.ts
- types/unified-tests.ts
remark, rehype, etc can be passed settings.
This creates a generic type that allows the language specific instances of `unified` to declare what options are supported.
Based off discussion from https://github.com/remarkjs/remark/pull/383#discussion_r302759676
> types: allow processors to declare options/settings

- types/index.d.ts
- types/unified-tests.ts
uses [variadic function](https://en.wikipedia.org/wiki/Variadic_function) with [tuple based type checking](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#tuples-in-rest-parameters-and-spread-expressions) to ensure settings and parameters match up.
resolves #60 by removing extra settings in favor of a variadic function.
---
There are some trade offs here, I've documented them to the best of my ability below.
> types: allow any number of settings to be passed to a plugin

- types/index.d.ts
- types/unified-tests.ts
Currently, [the types for this package](https://github.com/unifiedjs/unified/blob/b07233d0c32d47f4acb38cc51ca965e8157230f4/types/index.d.ts#L313) define that Transformers accept a `file` parameter that is `VFileCompatible`. The spec, on the other hand, states the type of the [`file` parameter is a `VFile`](https://github.com/unifiedjs/unified#function-transformernode-file-next).
The current definition is unergonomic because a plugin defined as:
```typescript
export default () => (node: Node, file: VFile) => {
// ...
};
```
...cannot be passed to `use` since `file: VFile` is incompatible with `file: VFileCompatible` (ironically):
```typescript
import plugin from '...';
unified().use(plugin);
```
causes:
```
Argument of type '() => (tree: Node, file: VFile) => Node' is not assignable to …
```
> Transformers take VFile instead of VFileCompatible

- types/index.d.ts
- types/unified-tests.ts
The current typings are defined such that [Parsers](https://github.com/unifiedjs/unified#processorparser) and [Compilers](https://github.com/unifiedjs/unified#processorcompiler) (and their respective functional variants) take `VFileCompatible` arguments (and, in the case of Parsers, has the wrong number of arguments). The truth is the spec states that they should accept `VFile` objects (and Parsers take two arguments), and the underlying implementation aligns with this:
* [Parsers are passed a `vfile()`'d argument](https://github.com/unifiedjs/unified/blob/b07233d0c32d47f4acb38cc51ca965e8157230f4/index.js#L270-L274)
* [Compilers are passed a `vfile()`'d argument](https://github.com/unifiedjs/unified/blob/b07233d0c32d47f4acb38cc51ca965e8157230f4/index.js#L340-L344)
* The `file` passed to …
> Fix Parser and Compiler types

- readme.md
- types/index.d.ts
Like https://github.com/rehypejs/rehype-highlight/blob/master/index.js#L30-L32, some transformers do not return a new tree.
> Fix transformer return type

- types/index.d.ts
- types/tslint.json
> fix dslint tests

- .github/workflows/ci.yml
Since unified is part of the actions beta, created a ci workflow, to try it out.
based off https://github.com/redotjs/redot/pull/17
:notebook: we already have Travis CI, so this would be a redundancy/backup.
> ci: add GitHub actions continuous integration workflow

- .github/workflows/ci.yml
resolves
```
Input 'version' has been deprecated with message: The version property will not be supported after October 1, 2019. Use node-version instead
```
> ci: rename version to node-version

- .github/workflows/ci.yml
- package.json
also split install and tests steps, this groups logs in a way that makes tracking down build failures easier.
> ci: add node 13 to test matrix

- readme.md
> Remove suggestion to install vfile types from `readme.md`

- index.js
- package.json
- readme.md
- test/process.js
unified is typically, but not always, used to *serialize* when it compiles.  Compilers don’t always return such a serialized (`string`, `Buffer`) though.  The previous behavior was to place the result of the stringify phase when processing on `file.contents`.  This doesn’t make sense for non-text.  This change places non-text results on `file.result`.
Closes vfile/vfile#45.
> Set `file.result` when processing to non-text

- readme.md
Changes Zeit branding to Vercel branding and uses the OC hosted image with black background.
White background can be found here: https://pbs.twimg.com/profile_images/1252525888710873088/CBm5_MB7_400x400.jpg but makes the logo appear smaller than the other gold sponsors.
> Update Vercel name and logo

- types/index.d.ts
- types/unified-tests.ts
A frozen processor has the same interface as a regular processor, except `use()`
is always disallowed.
This is related to remarkjs/remark#513
> Add `FrozenProcessor` interface to types

- readme.md
Currently `rehype-react` uses `vfile.result` instead of `vfile.contents`, and there are same sentances just below.
So I guess these lines are outdated...
> Remove outdated description of compile results

- test/freeze.js
- test/index.js
- test/process.js
- test/stringify.js
Hey, there.
Currently `npm test` throws the following error:
test/index.js:4:9
✖   4:9   Missing file extension for "./core"            import/extensions
✖   5:9   Missing file extension for "./freeze"          import/extensions
...
13 errors
This pull request fixes those errors and now all tests pass.
Hope you find this useful.
> Fix code-style

- index.js
- package.json
- types/index.d.ts
- types/tsconfig.json
- types/unified-tests.ts
Update typings to support ESM style imports (part of https://github.com/unifiedjs/unified/commit/dc46bc5a85d038566e226c388b58ff937341cbcf)
For now keeping the typings as a `.d.ts` file, JSDoc could be nice down the road, but overload support and split interfaces (`FrozenProcessor` vs `Processor`) are still challenging in JSDoc and potentially more difficult to maintain than the `.d.ts` file.
> Update typings to support ESM

- .github/workflows/main.yml
- index.js
- package.json
- test/index.js
- test/vfile-5.js
vfile@5 changed from the `contents` to the `value field.
Given that not all of the ecosystem has updated yet, and that some
version mismatches will occur for the foreseeable future, setting
both `contents` *and* `value` in those cases will hopefully alleviate
some of the struggles with updating.
Related to remarkjs/remark-frontmatter#16.
> Fix to set `vfile.value` if a vfile@5 is given

- types/index.d.ts
- types/unified-tests.ts
`.use` can be called with `true` or `false` to turn plugins on or off
> types: add support for boolean plugin options

- types/index.d.ts
Buffers, `null`/`undefined`, and `unknown` were not allowed from compilers.
While `string` is most often used as a return value, the other values should be allowed too
> types: add support for buffer, other return values

- package.json
*   [X] I read the support docs 
*   [X] I read the contributing guide 
*   [X] I agree to follow the code of conduct 
*   [X] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [X] If applicable, I’ve added docs and tests
This PR adds the latest version of `@types/unist` an explicit dependency (as we import from it directly).
Edit: I notice in the description that dependency on `@types/unist` is _suggested_ for projects using typescript - is there a particular downside to depending on it directly here?
> Add explicit dependency on `@types/unist`

- types/index.d.ts
… Plugin settings
Follow up to https://github.com/unifiedjs/unified/pull/145#discussion_r663525201
Tests for boolean support should still pass
https://github.com/unifiedjs/unified/blob/5167c49ce7e02fcd518adae0acda80ccd4e97400/types/unified-tests.ts#L80-L85
> Fix types to support booleans

- types/index.d.ts
- types/unified-tests.ts
follow up to https://github.com/unifiedjs/unified/pull/147 adding more test cases, covering typed plugins and plugin tuples
> Fix to improve plugin, plugin tuples with boolean options

- types/index.d.ts
- types/unified-tests.ts
* `next` can also be called w/o parameters, to just continue on
* `next` returns `void` (`return next()` is fine in a transformer)
> Fix `next` in types of transformer signature

- index.d.ts
- index.test-d.ts
- test/async-function.js
- test/run.js
- test/use.js
This allows plugins to define what type of tree they receive and yield in their transformer.
It does not prevent misuse of those plugins (such as a rehype plugin and then a remark plugin). Nor does it handle parser or compiler plugins.
> Add plugin tree type parameter

- index.d.ts
- index.test-d.ts
The 3rd overload signature (the promise variant) of `FrozenProcessor.run` now correctly accepts a tree of type `ParseTree` instead of `CompileTree`.
Fix #173.
> Fix type of `run` signature

- lib/index.js
- test/use.js
Empty presets are most likely a mistake by the user. At best, they do nothing.
This improves the situation for humans that make mistakes, by throwing a useful error.
Closes GH-200.
> Add useful error on empty presets

- .gitignore
- tsconfig.json
This enables “Go to Definition” in TypeScript based editors. Without a declaration map, this takes the user to the type definition. With a declaration map, this takes the user to the location in the source code.
The downside is, this means the source code needs to be published to npm as well. For projects using types in JSDoc this is not a problem, as the source code is already published as-is.
I’m creating a PR here to propose it, but I actually thing this is useful for all of unified. It might be too much work going over all packages …
> Add TypeScript declaration maps
